GET http://localhost:5189/games

###
GET http://localhost:5189/games/1

###
POST http://localhost:5189/games
Content-Type: application/json

{
    "name": "Kan2t",
    "genre": "Sexual and Nudity",
    "price": 0,
    "releaseDate": "2002-05-18"
}

###
PUT http://localhost:5189/games/1
Content-Type: application/json

{
    "name": "Fucko",
    "genre": "Fighting",
    "price": 1.99,
    "releaseDate": "2002-05-11"
}